### PR TITLE
Fix #46 - Use filter when writing pretty print JSON

### LINKED ISSUE #46: JsonMappingException - Can not resolve PropertyFilter with id 'bbox'
If I use this GTFS data:
http://gohart.org/google/google_transit.zip

...and run this command (using current master branch at fb2eb615f509efd1b0f57a8760a35b9eb795c6c2):

` java -jar target/gtfs-lib-2.2.0-SNAPSHOT-shaded.jar -validate google_transit.zip result.json`

I get this exception:

~~~
$ java -jar target/gtfs-lib-2.2.0-SNAPSHOT-shaded.jar -validate google_transit.zip result.json
[main] INFO com.conveyal.gtfs.model.Entity$Loader - Table feed_info was missing but it is not required.
[main] INFO com.conveyal.gtfs.GTFSFeed - Feed ID is undefined, pester maintainers to include a feed ID. Using file name google_transit.
[main] INFO com.conveyal.gtfs.model.Entity$Loader - Loading GTFS table agency from agency.txt
[main] INFO com.conveyal.gtfs.model.Entity$Loader - Loading GTFS table calendar from calendar.txt
[main] INFO com.conveyal.gtfs.model.Entity$Loader - Loading GTFS table calendar_dates from calendar_dates.txt
[main] INFO com.conveyal.gtfs.model.Entity$Loader - Loading GTFS table fare_attributes from fare_attributes.txt
[main] INFO com.conveyal.gtfs.model.Entity$Loader - Loading GTFS table fare_rules from fare_rules.txt
[main] INFO com.conveyal.gtfs.model.Entity$Loader - Loading GTFS table routes from routes.txt
[main] INFO com.conveyal.gtfs.model.Entity$Loader - Loading GTFS table shapes from shapes.txt
[main] INFO com.conveyal.gtfs.model.Entity$Loader - Loading GTFS table stops from stops.txt
[main] INFO com.conveyal.gtfs.model.Entity$Loader - Table transfers was missing but it is not required.
[main] INFO com.conveyal.gtfs.model.Entity$Loader - Loading GTFS table trips from trips.txt
[main] INFO com.conveyal.gtfs.model.Entity$Loader - Table frequencies was missing but it is not required.
[main] INFO com.conveyal.gtfs.model.Entity$Loader - Loading GTFS table stop_times from stop_times.txt
[main] INFO com.conveyal.gtfs.GTFSFeed - 0 errors
[main] INFO com.conveyal.gtfs.GTFSFeed - Building stop to stop times index
[main] INFO com.conveyal.gtfs.GTFSFeed - Building trips per service index
[main] INFO com.conveyal.gtfs.GTFSFeed - Building services per date index
[main] INFO com.conveyal.gtfs.GTFSFeed - Generating unique names for patterns
[main] INFO com.conveyal.gtfs.GTFSFeed - Total patterns: 140
[main] INFO com.conveyal.gtfs.GTFSFeed - DuplicateStopsValidator finished in 1894 milliseconds.
[main] INFO com.conveyal.gtfs.GTFSFeed - HopSpeedsReasonableValidator finished in 0 milliseconds.
[main] INFO com.conveyal.gtfs.GTFSFeed - MisplacedStopValidator finished in 247 milliseconds.
[main] INFO com.conveyal.gtfs.GTFSFeed - NamesValidator finished in 13 milliseconds.
[main] INFO com.conveyal.gtfs.GTFSFeed - OverlappingTripsValidator finished in 204 milliseconds.
[main] INFO com.conveyal.gtfs.GTFSFeed - ReversedTripsValidator finished in 514 milliseconds.
[main] INFO com.conveyal.gtfs.GTFSFeed - TripTimesValidator finished in 391 milliseconds.
[main] INFO com.conveyal.gtfs.GTFSFeed - UnusedStopValidator finished in 5 milliseconds.
[main] INFO com.conveyal.gtfs.GTFSFeed - 8 validators completed in 3269 milliseconds.
Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: Can not resolve PropertyFilter with id 'bbox'; no FilterProvider configured (through reference chain: com.conveyal.gtfs.validator.model.ValidationResult["feedStatistics"]->com.conveyal.gtfs.stats.model.FeedStatistic["bounds"])
        at com.fasterxml.jackson.databind.ser.std.StdSerializer.findPropertyFilter(StdSerializer.java:274)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFieldsFiltered(BeanSerializerBase.java:683)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:150)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:541)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:644)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:152)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:541)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:644)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:152)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:114)
        at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:809)
        at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:684)
        at com.conveyal.gtfs.util.json.JsonManager.writePretty(JsonManager.java:73)
        at com.conveyal.gtfs.GTFSMain.main(GTFSMain.java:47)
~~~

### PR DESCRIPTION
**Pull request by barbeau**
* Refactor filters variable to be class member so it can be re-used later with ObjectMapper member variable for pretty print
* Rename writer/mapper variables to make it clearer which is being used
* Fix Javadoc for constructor

### CODE REVIEW

**Comment by landonreed** [comment]
@mattwigway, it looks like these PRs using forked branches are failing in Travis due to a maven signing issue.  Do you know how to fix this?

**Comment by barbeau** [comment]
Looks like this is the Travis issue for PR builds:
https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions

**Comment by landonreed** [comment]
Ah, right.  It looks like that PR logic is being used for the script (`mvn clean` vs `mvn deploy`) already.  Maybe the `before_install` step needs the same conditional.

**Comment by barbeau** [comment]
>Maybe the before_install step needs the same conditional.

Yeah, I think that would fix it.  Let me open another separate PR for this.

**Comment by barbeau** [comment]
Ok, just opened a new PR here for Travis (just force-pushed a new commit to fix my initial one):
https://github.com/conveyal/gtfs-lib/pull/50

There's still a syntax error, though - let me peck at this some more...

**Comment by barbeau** [comment]
Ok, Travis should be fixed via https://github.com/conveyal/gtfs-lib/pull/50 now.

**Comment by barbeau** [comment]
So, I believe if you merge #50, and then restart the Travis build for this PR, this PR should pass.

**Comment by landonreed** [comment]
@barbeau, I think this branch needs to be rebased on `master`.  The Travis build still seems to be failing.

**Comment by barbeau** [comment]
Ok, just rebased and force-pushed.  Hopefully it should pass now...

**Comment by barbeau** [comment]
Yup, we should be good now!  It passed!

**Pull request merged**
