### PR TITLE
Add stop headsigns

### PR DESCRIPTION
**Pull request by philip-cline**
### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

This PR adds support for stop headsigns

### CODE REVIEW

**Review by br648 — CHANGES_REQUESTED** [review]
Look to update in these locations as well. This sort of update is a PITA. I did a search for an existing param (pickup_type) to find these:

com.conveyal.gtfs.loader.EntityPopulator<T> -> PATTERN_STOP (line 56) needs to be updated.
com.conveyal.gtfs.loader.JdbcTableWriter -> Around line 1152 needs to be updated.

It would also be benifical to update some of the unit tests to confirm loading and reading of this new value.

Update these files:
- resources/graphql/feedPattern.txt (add stop_headsign under pattern_stops)
- resources/fake-agency/stop_times.txt (include a stop_headsign value on first row)

Update these related tests:

GTFSGraphQLTest -> canFetchPatterns()
- Update canFetchPatterns-0.json with new expected output
- Update canFetchStopTimes-0.json with new expect output

GTFSTest -> canLoadAndExportSimpleAgency()
- Add new RecordExpectation around line 1293

**Review by br648 — APPROVED** [review]
Looks good and all relevant tests pass. Nice one!

**Review by binh-dam-ibigroup — APPROVED** [review]
Looks solid

**Comment by binh-dam-ibigroup** [comment]
@philip-cline You will have to update the databases when deploying this change, so that existing feeds and editor snapshots get access to the stop headsign field without crashing.

**Pull request merged**
